# Generated by Django 4.2.2 on 2023-06-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_dish_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
